"""Bhowmik et al. (1982) empirical ship-wake model.

Reference
---------
Bhowmik, N.G., Demissie, M. and Guo, C.Y. (1982). Waves and Drawdown
Generated by River Traffic on the Illinois and Mississippi Rivers.
Illinois State Water Survey, Report of Investigation 101.

Description
-----------
Simple draught-Froude scaling. No lateral-distance dependency.

    Froude_Draft = V / sqrt(g * d)
    Hmax         = 0.133 * Froude_Draft * d

where:
    V — vessel speed (m/s)
    d — vessel draught (m)
    g — gravitational acceleration (m/s²)
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def compute_bhowmik(
    df: pd.DataFrame,
    g: float = 9.78,
) -> pd.Series:
    """Apply the Bhowmik et al. (1982) formula to each AIS fix.

    Parameters
    ----------
    df: DataFrame with ``SOGms``, ``draught`` columns.
    g:  Gravitational acceleration (m/s²). Default 9.78 (Singapore).

    Returns
    -------
    pd.Series of Hmax values (m).
    """
    v = df["SOGms"].to_numpy(dtype=float)
    draught = df["draught"].to_numpy(dtype=float)

    Froude_Draft = v / np.sqrt(g * draught)
    hmax = 0.133 * Froude_Draft * draught

    return pd.Series(hmax, index=df.index, name="H_Bhowmik")
